// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcEY_JuOszJIXxpQUAQnqlhPMb5_L0fls',
    appId: '1:522347500122:web:91b6568fc042cc28cebe63',
    messagingSenderId: '522347500122',
    projectId: 'vitalisstudio-6bb26',
    authDomain: 'vitalisstudio-6bb26.firebaseapp.com',
    storageBucket: 'vitalisstudio-6bb26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEggNt4aWrVC5NmZHPmPbaIw1dj4BLI0I',
    appId: '1:522347500122:android:e004dabc9d5168a6cebe63',
    messagingSenderId: '522347500122',
    projectId: 'vitalisstudio-6bb26',
    storageBucket: 'vitalisstudio-6bb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkz2pGj-sT_24ksA-YTEuL3OIAf1Zx2k',
    appId: '1:522347500122:ios:41b3bc0657eec054cebe63',
    messagingSenderId: '522347500122',
    projectId: 'vitalisstudio-6bb26',
    storageBucket: 'vitalisstudio-6bb26.firebasestorage.app',
    androidClientId: '522347500122-ifoj8c5a9cg3avjro16niad3r68cufmf.apps.googleusercontent.com',
    iosClientId: '522347500122-mfh8omm0ki79t88gl0om3o7dif4bpsng.apps.googleusercontent.com',
    iosBundleId: 'solumK.vitalisstudio.vitalisstudio',
  );
}
